<?php

namespace app\api\controller;

use think\facade\Lang;

/**
 * ============================================================================
 * DSShop多用户商城
 * ============================================================================
 * 版权所有 2014-2028 长沙德尚网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.csdeshang.com
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和使用 .
 * 不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * 控制器
 */
class Pointshop extends MobileMall
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        Lang::load(base_path().'home/lang/'.config('lang.default_lang').'/pointprod.lang.php');
        Lang::load(base_path().'home/lang/'.config('lang.default_lang').'/voucher.lang.php');
        //判断系统是否开启积分兑换功能
        if (config('ds_config.points_isuse') != 1 || config('ds_config.pointprod_isuse') != 1) {
            ds_json_encode(10001, lang('pointshop_unavailable'));
        } 
    }
    public function index(){

        $result=array();
        //开启代金券功能后查询推荐的热门代金券列表
        if (config('ds_config.voucher_allow') == 1){
            $recommend_voucher = model('voucher')->getRecommendTemplate(6);
            $result['recommend_voucher']=$recommend_voucher;
        }
        //开启积分兑换功能后查询推荐的热门兑换商品列表
        if (config('ds_config.pointprod_isuse') == 1){
            //热门积分兑换商品
            $recommend_pointsprod = model('pointprod')->getRecommendPointProd(10);
            $result['recommend_pointsprod']=$recommend_pointsprod;
        }

        ds_json_encode(10000, '', $result);
    }

}